services:
  - type: web
    name: document-intelligence-api
    runtime: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: MAX_UPLOAD_MB
        value: 25

  - type: web
    name: document-intelligence-ui
    runtime: docker
    plan: free
    region: ohio
    dockerContext: .
    dockerfilePath: ./Dockerfile
    dockerCommand: streamlit run app/streamlit_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: API_HOST
        fromService:
          type: web
          name: document-intelligence-api
          property: host
      - key: API_PORT
        fromService:
          type: web
          name: document-intelligence-api
          property: port
