[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4c5fe9"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f7f8fd"
textColor = "#132b60"
font = "sans serif"
